name: release-tagging

on: 
    workflow_call: 
        inputs:
            version_info:
                description: 'Provides the version information for the tagging the image'
                required: true
                type: string

jobs:
    release-tagging:
        runs-on: [ ubuntu-latest ]
        timeout-minutes: 10

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Tag release
              run: |
                ${{ github.workspace }}/push_tag.sh ${{ inputs.version_info }} ${{ secrets.DOCKER_REGISTRY_PAT }}
